config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resource :search, only: [:create, :show]
  resources :tickets, only: [:create, :show, :new, :destroy, :index]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_station_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member    
    end
    resources :routes
    resources :users
    resources :wagons 
    resources :sv_wagons,   controller: "wagons", type: "SvWagons"
    resources :coupe_wagons,   controller: "wagons", type: "CoupeWagons"
    resources :plackart_wagons,   controller: "wagons", type: "PlackartWagons"
    resources :sit_wagons,   controller: "wagons", type: "SitWagons"
    resources :tickets
  end

  root 'searches#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ActiveRecord::Base
   validates :name, presence: true
   validate :stations_count

   has_many :trains
   has_many :railway_stations_routes
   has_many :railway_stations, through: :railway_stations_routes
   before_validation :set_name
   
 
   private

    def set_name
      self.name = "#{self.railway_stations.first.title} - #{self.railway_stations.last.title}"
    end

     def stations_count
      if railway_stations.size < 2
        errors.add(:base, "Route should contain at least 2 stations")
      end
    end

    

end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end
  
  def show
  end
    
  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
   	  redirect_to admin_routes_path, notice: 'Route was successfully updated.'
    else
    	render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
   	  redirect_to [:admin, @route]
    else
    	render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
  	@route = Route.find(params[:id])
  end

  def route_params
  	params.require(:route).permit(:name, :train_id, railway_station_ids: [])
  end

end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{ hidden ? 'none' : 'block'}"} do |form| %>
  <%= render 'common/errors', resourse:route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field  :name, id: :route_name %>
  </div>

    <div class="field">
    <%= form.label :railway_station_ids, 'Выбрать станции' %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, {multiple: true} %>
 
  </div>

  <div class="actions">
    <%= form.submit t("#{route.new_record? ? :create : :update}"), :class => 'btn btn-warning btn-outline-primary border border-light'%>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
 <tr>
    <td> <%= route.name %></td>
 
    <td><%= link_to 'Показать', [:admin, route] %></td>
    <td><%= link_to 'Редактировать', edit_admin_route_path(route) %></td>
    <td><%= link_to 'Удалить', [:admin, route], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
 </tr>

app/views/admin/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список маршрутов</h1>

<table class="table table-striped text-dark bg-light">
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @routes.each do |route| %> 
      <tr>
        <td>
        <div id="route_name_<%= route.id %>">
         <%= route.name  %>
        </div>
             <%= render 'form', route: route,  hidden: true %>
           
        </td>
            <td><%= link_to t('common.show'), [:admin, route] %></td>
            <td><%= link_to t('common.edit'), '', class: 'edit_route', data: { route_id: route.id }%></td>
            <td><%= link_to t('common.delete'), [:admin, route], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить маршрут', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>Добавить маршрут</h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.name %>
</p>

<p>
  <strong><%= t('admin.routes.trains') %></strong>
  <% if @route.trains.present? %>
    <% @route.trains.each do |train| %>
      <%= train.number %>
    <% end %>
  <% else %>
  <%= t('admin.routes.trains_absents') %>
  <% end %>
</p>
<p>
  <strong><%= t('admin.routes.stations') %> </strong>
  <% if @route.railway_stations.empty? %>
    <%= t('admin.routes.stations_absents') %>
     <% else %>
    <table class="table table-striped  text-dark" style="background-color:#008000">
      <thead>
       <tr>
        <td width="100px">Название</td>
        <td>Позиция</td>
        <td>Время прибытия</td>
        <td>Время отправления</td>
       </tr>
      </thead>
    <tbody>
     <% @route.railway_stations.ordered.each do |station| %>
      <tr>
       <td><%= station.title %></td>
       <td>
        <%= form_tag update_station_number_admin_railway_station_path(station), method: :patch do %>
          <%= number_field_tag :station_number, station.station_number_in(@route)%> 
          <%= hidden_field_tag :route_id, @route.id %>
          <%= submit_tag "Изменить" %>
         <% end %>
        </td>

        <td>
        <%= form_tag update_arrival_time_admin_railway_station_path(station), method: :patch do %>
          <%= time_field_tag :arrival_time, station.arrival_time_in(@route) %>
          <%= hidden_field_tag :route_id, @route.id %>
          <%= submit_tag "Изменить" %>
         <% end %>
        </td>

        <td>
        <%= form_tag update_departure_time_admin_railway_station_path(station), method: :patch do %>
          <%= time_field_tag :departure_time, station.departure_time_in(@route) %>
          <%= hidden_field_tag :route_id, @route.id %>
          <%= submit_tag "Изменить" %>
         <% end %>
        </td>
          
       </tr>
      <% end %>
     </tbody>
    </thead>
   <% end %>
  </p>  
<p>
<td><%= link_to 'Редактировать', edit_admin_route_path(@route) %></td>
<td><%= link_to 'Назад', admin_routes_path %></td>
</p>