config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resource :search, only: [:create, :show]
  resources :tickets, only: [:create, :show, :new, :destroy, :index]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_station_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member    
    end
    resources :routes
    resources :users
    resources :wagons 
    resources :sv_wagons,   controller: "wagons", type: "SvWagons"
    resources :coupe_wagons,   controller: "wagons", type: "CoupeWagons"
    resources :plackart_wagons,   controller: "wagons", type: "PlackartWagons"
    resources :sit_wagons,   controller: "wagons", type: "SitWagons"
    resources :tickets
  end

  root 'searches#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Привет! Rails!</h1>

 <p>
<% if user_signed_in? %>
   <% if current_user.admin? %>
      <%= link_to 'Список билетов', admin_tickets_path  %>
</p>
<p>
      <%= link_to 'Список станций', admin_railway_stations_path %>
</p>
<p>
<%= link_to 'Список поездов', admin_trains_path %>
</p>
<p>
<%= link_to 'Список маршрутов', admin_routes_path %>
</p>
    <% else %>
      <%= link_to 'Список билетов', tickets_path %> 
    <% end %>   
<% end %>
</p>
 <p>
<%= link_to 'Найти билет', search_path %>
</p>