config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resource :search, only: [:create, :show]
  resources :tickets, only: [:create, :show, :new, :destroy, :index]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_station_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member    
    end
    resources :routes
    resources :users
    resources :wagons 
    resources :sv_wagons,   controller: "wagons", type: "SvWagons"
    resources :coupe_wagons,   controller: "wagons", type: "CoupeWagons"
    resources :plackart_wagons,   controller: "wagons", type: "PlackartWagons"
    resources :sit_wagons,   controller: "wagons", type: "SitWagons"
    resources :tickets
  end

  root 'searches#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_stations, only: [:create]
  before_action :set_user

  def show
    
  end

  def create
   
   @routes = RailwayStation.select_routes(@base_station, @end_station) 
   
   render :show
 
  end

  private  

  def set_stations
   @base_station = RailwayStation.find(params[:base_station_id])
   @end_station = RailwayStation.find(params[:end_station_id])
  end

  def set_user
   if user_signed_in?
     @user ||= current_user
   else
     @user = User.first
   end
  end
end

app/views/searches/show.html.erb
<h1>Поиск билета</h1>
 
<div class="shadow container-fluid bg-info text-warning" >
 
  <%= form_tag search_path, method: :post do %>
  <div class= "row" %>
    <div class= "col-md-5" %>
    <%= label_tag :base_station, 'Выбрать станцию отправления' %>
    <%= select_tag :base_station_id, options_from_collection_for_select(RailwayStation.all, :id, :title, {})  %>
     </div>
    <div class= "col-md-5" %>
    <%= label_tag :end_station, 'Выбрать станцию назначения' %>
    <%= select_tag :end_station_id, options_from_collection_for_select(RailwayStation.all, :id, :title, {})  %> 
     </div>

  <div class= "col-md-2 text-right" %>
    <button class="btn btn-primary btn-lg border border-light " type="submit">Найти</button>
  </div>

  <% end %> 
 </div><!--/row/-->
</div><!--/container/-->
 
<p>
 <h3>Результат поиска:</h3>
 
  <% if @routes.present? %>

   <table class="table table-striped  text-light " id="some_id" >
     <thead>
      <tr>
        
        <td width="400">    Время отправления от станции  
 <p>
        <%= @base_station.title %>
        </td>
        <td width="400">     Время прибытия на станцию  
<p>
        <%= @end_station.title %>
        </td>
        <td width="250">  Номер поезда     </td>
        <td>  </td>     
      </tr>
    </thead> 
    <tbody>  
      <tr>
       <% @routes.each do |route| %>
         <% if RailwayStation.find(@base_station.id).station_number_in(route) < RailwayStation.find(@end_station.id).station_number_in(route) && route.trains.present? %>   
          <% route.trains.each do |train| %>
   
       
       <td><%= RailwayStation.find(@base_station.id).departure_time_in(route) %></td>
       <td><%= RailwayStation.find(@end_station.id).arrival_time_in(route) %></td> 
       <td><%= train.number %></tSd>
       <td>
 
       
       <% if user_signed_in?  %>
       
       <%= form_tag (current_user.admin? ? new_admin_ticket_path : new_ticket_path), method: :get do %>
         <%= hidden_field_tag :train_id, train.id %>
         <%= hidden_field_tag :base_station_id, @base_station.id %>
         <%= hidden_field_tag :end_station_id, @end_station.id %>
         <%= hidden_field_tag :user_id, @user.id %>
          <button class="btn btn-warning border border-light" type="submit">Купить билет</button>
       <% end %>
        <% else%>
           <h6>Чтобы купить билет войдите или зарегистрируйтесь.</h6>
           <% end %>
       </td>      
    </tr>
   </div>
     <% end %> 
    <% end %>
   
  <% end %> 

     </tbody>
   </table>
 
  
    <% else %>
  <div class="shadow container-right col-md-4 bg-danger text-light" >  
   Маршрут отсутствует
   </div>
<% end %>