config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resource :search, only: [:create, :show]
  resources :tickets, only: [:create, :show, :new, :destroy, :index]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_station_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member    
    end
    resources :routes
    resources :users
    resources :wagons 
    resources :sv_wagons,   controller: "wagons", type: "SvWagons"
    resources :coupe_wagons,   controller: "wagons", type: "CoupeWagons"
    resources :plackart_wagons,   controller: "wagons", type: "PlackartWagons"
    resources :sit_wagons,   controller: "wagons", type: "SitWagons"
    resources :tickets
  end

  root 'searches#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ActiveRecord::Base
	validates :number, presence: true
        validates :number, numericality: { only_integer:true }
        validates :number, uniqueness: true

	belongs_to :route, optional: true
	belongs_to :current_station, optional: true, class_name: 'RailwayStation', foreign_key: :current_station_id
        has_many :tickets
        has_many  :wagons 
 
    def place_count (type, place)
     place_count = self.wagons.where(type: type).sum(place) 
    end

  
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
      redirect_to admin_trains_url, notice: 'Train was successfully destroyed.'
  end

  private
   
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :sort_wagons)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{ hidden ? 'none' : 'block'}"}  do |form| %>
  <%= render 'common/errors', resourse: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :train_number %>
  </div>
 <p>
   <div class="field">
     <%= form.label :sort_wagons %>
     <%= form.radio_button(:sort_wagons, true) %>
     <%= label_tag(:sort_wagons, "С головы поезда") %>
     <%= form.radio_button(:sort_wagons, false ) %>
     <%= label_tag(:sort_wagons, "С хвоста поезда") %>
   </div>
 </p>
 <p>
  <div class="field">
    <%= form.label :current_station %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title, include_blank: true %>
  </div>
 </p>
 <p>
  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name, include_blank: true %>
  </div>
</p>
<p>
  <div class="actions">
    <%= form.submit %>
  </div>
</p>
<% end %>

app/views/admin/trains/edit.html.erb
<h1> <%= t('.title')%></h1>

<%= render 'form', train: @train, hidden: false %>
|
<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table class="table table-striped text-dark " href="app/assets/stylesheets/style.css" >
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %> 
      <tr>
        <td>
        <div id="train_number_<%= train.id %>">
         <%= train.number  %>
        </div>
             <%= render 'form', train: train,  hidden: true %>
           
        </td>
            <td><%= link_to t('common.show'), [:admin, train] %></td>
            <td><%= link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id }%></td>
            <td><%= link_to t('common.delete'), [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать поезд', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('admin.trains.number') %></strong>
  <%= @train.number %>
</p>
  <strong><%= t('admin.trains.current_station') %></strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %> 
  <% else %>
   Не указано
  <% end %>

 <p>
  <strong><%= t('admin.trains.wagons') %> </strong>
  <% if @train.wagons.any? %>
    <%=  @train.wagons.count %>
    <% else %>
    В поезде нет вагонов
  <% end %>
  </p>

<p>
  <%= @train.sort_wagons ? t('admin.trains.head') : t('admin.trains.tail') %>
</p>
  
   <% @train.wagons.ordered(@train).each do |wagon| %>
     <%= link_to "Вагон № #{wagon.number}", [:admin, wagon] %> |
   <% end %>
 </p
 <p>
   <%= link_to 'Добавить вагон', new_admin_train_wagon_path(@train) %>
 </p>

<p>
<% Wagon::TYPE_WAGON.each do |type| %>
     <%= @train.wagons.where(type: type).count %>
     <%= type %>
 :
    <% Wagon::PLACE.each do |place| %>
      <%= place %>
 - 
    <%= @train.place_count(type, place) %>
;
   <% end %>

<% end %>
</p>

<p>
  <strong><%= t('admin.trains.route') %></strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
   <%= t('admin.trains.route_absents')%>
  <% end %>
 
</p>
<%= link_to t('common.edit'), edit_admin_train_path(@train) %>
<%= link_to t('common.back'), admin_trains_path %>